image: python:3.10-slim

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - mv application/.env_pipline application/.env
            - pip install --upgrade pip setuptools wheel
            - pip install -r requirements.txt
            - python3 application/manage.py test main.tests


