# Generated by Django 3.2.16 on 2023-01-09 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtitle', models.CharField(max_length=100, verbose_name='Посада')),
                ('Company', models.CharField(max_length=50, verbose_name='Компания')),
                ('Discription', models.TextField(verbose_name='Опис')),
                ('JobDate', models.CharField(max_length=10, verbose_name='Дата')),
                ('Salary', models.IntegerField(verbose_name='Заробiтна плата')),
                ('Region', models.CharField(max_length=30, verbose_name='Регiон')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Записи о вакансиях',
                'verbose_name_plural': 'Записи о вакансиях',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='CommentId')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='CreateDate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vacancy')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
