# Generated by Django 3.2.16 on 2022-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221219_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='Company',
            field=models.CharField(max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobDate',
            field=models.IntegerField(max_length=4, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Region',
            field=models.CharField(max_length=30, verbose_name='Регiон'),
        ),
    ]
