# Generated by Django 3.2.16 on 2022-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_job_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Region',
            field=models.TextField(default=1, verbose_name='Регион'),
            preserve_default=False,
        ),
    ]
