# Generated by Django 3.2.16 on 2022-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221219_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Region',
            field=models.CharField(max_length=100, verbose_name='Регiон'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Salary',
            field=models.IntegerField(verbose_name='Заробiтна плата'),
        ),
    ]
