# Generated by Django 3.2.16 on 2022-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221219_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Vacancy',
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Записи о вакансиях', 'verbose_name_plural': 'Записи о вакансиях'},
        ),
    ]
