# Generated by Django 3.2.16 on 2022-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vacancy_jobdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='JobDate',
            field=models.CharField(max_length=10, verbose_name='Дата'),
        ),
    ]
